"""End-to-end tests for the sizing endpoints and the vendored catalog.

The catalog-integrity tests matter more than they look: the catalog is
regenerated by hand from Oracle's docs and Hugging Face, so a silent scraper
regression — a renamed shape, a family page that stopped parsing, an
architecture field that vanished — would not break any code path. It would just
quietly shrink what the tab can answer. These assert the shape of the data, not
its contents, so they survive Oracle publishing new models.
"""
from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from waqil_api.dac_catalog import DacCatalog
from waqil_api.dac_service import DacService
from waqil_api.contracts import DacRecommendRequestV1


@pytest.fixture(scope="module")
def catalog() -> DacCatalog:
    return DacCatalog()


# ── Catalog integrity ────────────────────────────────────────────────────────


def test_catalog_loads_models_shapes_and_gpus(catalog: DacCatalog):
    assert len(catalog.models) > 50
    assert len(catalog.shapes) >= 24
    assert {"A10", "A100_40G", "A100_80G", "H100", "H200", "B200"} <= set(catalog.gpus)


def test_every_shape_resolves_to_a_known_gpu(catalog: DacCatalog):
    for shape in catalog.shapes.values():
        assert shape.gpu.key in catalog.gpus
        assert shape.gpu_count >= 1
        assert shape.ai_units > 0


def test_every_validated_shape_oracle_lists_actually_exists(catalog: DacCatalog):
    """A shape name Oracle publishes must resolve, directly or via an alias.

    Oracle spells the same shape both ways across pages (A100_80GB_X2 and
    A100_80G_X2). If an alias is dropped the model silently loses its only
    validated shape and drops out of every recommendation.
    """
    unresolved = [
        (record.id, name)
        for record in catalog.models.values()
        for name in record.validated_shapes
        if catalog.shape(name) is None
    ]
    assert not unresolved, f"unresolved validated shapes: {unresolved[:5]}"


def test_supported_models_carry_the_fields_the_kv_math_needs(catalog: DacCatalog):
    supported = [record for record in catalog.models.values() if record.architecture]
    assert len(supported) > 50
    for record in supported:
        architecture = record.architecture
        assert architecture is not None
        assert architecture.num_layers > 0
        assert architecture.hidden_size > 0
        assert architecture.num_key_value_heads > 0
        assert architecture.head_dim > 0
        assert architecture.attention_type in ("mha", "gqa", "mla")


def test_unsupported_models_say_why_rather_than_going_blank(catalog: DacCatalog):
    """A model Oracle validates but the roofline cannot describe still explains itself."""
    unsupported = [record for record in catalog.models.values() if not record.architecture]
    for record in unsupported:
        assert record.unsupported_reason, f"{record.id} has no explanation"
    # Image and audio models are the expected members of that set.
    assert any(
        record.capability not in ("TEXT_TO_TEXT", "IMAGE_TEXT_TO_TEXT")
        for record in unsupported
    )


def test_mixture_of_experts_models_record_their_expert_split(catalog: DacCatalog):
    moe = [
        record
        for record in catalog.models.values()
        if record.architecture and record.architecture.is_moe
    ]
    assert moe, "expected MoE models in the import catalog"
    for record in moe:
        architecture = record.architecture
        assert architecture is not None
        assert architecture.params_expert_total > 0
        assert 0 < architecture.params_expert_active <= architecture.params_expert_total


def test_calibration_joins_benchmarks_to_catalog_models(catalog: DacCatalog):
    """The benchmark join has to keep working, or calibration silently empties."""
    assert catalog.calibration_samples
    assert catalog.coefficients.fitted
    assert catalog.coefficients.decode_median_error is not None


def test_provenance_reports_dates_and_the_unverified_price(catalog: DacCatalog):
    provenance = catalog.provenance()
    assert provenance["models"]["generated_at"]
    assert provenance["benchmarks"]["generated_at"]
    # The dollar rate is not scrapeable, and the UI must be able to say so.
    assert provenance["pricing"]["rate_verified"] is False
    assert provenance["calibration"]["sample_rows"] > 0


# ── HTTP surface ─────────────────────────────────────────────────────────────


def test_catalog_endpoint_returns_models_shapes_and_provenance(client: TestClient):
    response = client.get("/api/v1/dac/catalog")
    assert response.status_code == 200
    body = response.json()
    assert body["models"] and body["shapes"] and body["gpus"]
    assert body["quantizations"]
    assert body["provenance"]["calibration"]["fitted"] is True


def _first_supported(client: TestClient) -> dict:
    body = client.get("/api/v1/dac/catalog").json()
    for model in body["models"]:
        if model["supported"] and model["validated_shapes"]:
            return model
    raise AssertionError("no supported model with a validated shape in the catalog")


def test_estimate_endpoint_returns_a_full_breakdown(client: TestClient):
    model = _first_supported(client)
    response = client.post(
        "/api/v1/dac/estimate",
        json={
            "model_id": model["id"],
            "shape": model["validated_shapes"][0],
            "concurrency": 8,
            "prompt_tokens": 2000,
            "response_tokens": 200,
        },
    )
    assert response.status_code == 200
    body = response.json()
    assert body["vram"]["total_gb"] > 0
    assert body["performance"]["inference_speed_tps"] > 0
    assert body["confidence"]["tier"] in ("measured", "interpolated", "modeled")
    assert body["cost"]["unit_hours"] > 0
    assert body["oracle_validated"] is True


def test_estimate_rejects_an_unknown_model_with_a_readable_error(client: TestClient):
    response = client.post(
        "/api/v1/dac/estimate", json={"model_id": "nope/not-a-model", "shape": "H100_X1"}
    )
    assert response.status_code == 400
    assert "nope/not-a-model" in response.json()["detail"]


def test_estimate_rejects_an_unknown_shape(client: TestClient):
    model = _first_supported(client)
    response = client.post(
        "/api/v1/dac/estimate", json={"model_id": model["id"], "shape": "GB200_X99"}
    )
    assert response.status_code == 400


def test_optimize_endpoint_ranks_configurations(client: TestClient):
    model = _first_supported(client)
    response = client.post(
        "/api/v1/dac/optimize",
        json={"model_id": model["id"], "concurrency": 8, "max_request_latency_s": 60},
    )
    assert response.status_code == 200
    body = response.json()
    assert body["options"]
    compliant = [option for option in body["options"] if option["meets_sla"]]
    costs = [option["cost"]["unit_hours"] for option in compliant]
    assert costs == sorted(costs), "compliant options must be ordered cheapest first"


def test_optimize_explains_an_unreachable_target(client: TestClient):
    model = _first_supported(client)
    response = client.post(
        "/api/v1/dac/optimize",
        json={"model_id": model["id"], "concurrency": 64, "max_request_latency_s": 0.001},
    )
    assert response.status_code == 200
    body = response.json()
    assert not any(option["meets_sla"] for option in body["options"])
    assert body["notes"]


def test_recommend_endpoint_ranks_models_for_a_use_case(client: TestClient):
    response = client.post(
        "/api/v1/dac/recommend",
        json={"use_case": "A coding assistant for our internal Python services", "limit": 5},
    )
    assert response.status_code == 200
    body = response.json()
    assert body["candidates"]
    assert all(candidate["shape"] for candidate in body["candidates"])


def test_recommend_switches_capability_for_a_vision_use_case(client: TestClient):
    response = client.post(
        "/api/v1/dac/recommend",
        json={"use_case": "Read scanned invoices and screenshots into structured data"},
    )
    assert response.status_code == 200
    capabilities = {candidate["capability"] for candidate in response.json()["candidates"]}
    assert capabilities == {"IMAGE_TEXT_TO_TEXT"}


def test_combined_coding_and_extraction_prompt_gets_a_diverse_judge_pool(
    catalog: DacCatalog,
):
    """Old VL naming must not crowd newer multimodal models out of consideration."""
    request = DacRecommendRequestV1(
        use_case=(
            "Two use cases: 1. Coding assistant "
            "2. Document/image extraction solution"
        )
    )
    service = DacService(catalog)

    visible = service._shortlist(request)
    assert len({candidate.family for candidate in visible}) > 1

    judged = service._shortlist(request, candidate_limit=12)
    judged_ids = {candidate.model_id for candidate in judged}
    assert "google/gemma-4-31B-it" in judged_ids
    assert "Qwen/Qwen3.6-35B-A3B" in judged_ids


def test_request_validation_rejects_nonsense_load(client: TestClient):
    model = _first_supported(client)
    response = client.post(
        "/api/v1/dac/estimate",
        json={"model_id": model["id"], "shape": model["validated_shapes"][0], "concurrency": 0},
    )
    assert response.status_code == 422


# ── Recommender degradation ──────────────────────────────────────────────────


class ExplodingModel:
    """A provider that fails the way a stopped Ollama does."""

    name = "exploding"

    async def generate(self, request, on_token=None, *, model_aliases=None, on_reasoning=None):
        raise RuntimeError("model backend unreachable")


class ReorderingModel:
    """A provider that returns a valid reordering plus a bogus extra model."""

    name = "reordering"

    def __init__(self, order: list[str]) -> None:
        self._order = order
        self.seen_aliases: dict | None = None

    async def generate(self, request, on_token=None, *, model_aliases=None, on_reasoning=None):
        import json as _json

        from waqil_api.contracts import ModelResultV1

        self.seen_aliases = model_aliases
        payload = {
            "order": [*self._order, "hallucinated/model-that-does-not-exist"],
            "rationales": {self._order[0]: "Best fit for the stated task."},
            "summary": "Pick the first one.",
        }
        return ModelResultV1(model="fake-model", content=_json.dumps(payload))


@pytest.mark.anyio
async def test_recommendation_survives_a_dead_model_backend(catalog: DacCatalog):
    """A model outage must cost the prose, never the ranking.

    Sizing and cost are computed by the host and are exact; only the judgement
    of task fit depends on the model. Losing the whole answer because Ollama is
    stopped would make the tab useless in exactly the offline case Metis exists
    to serve.
    """
    service = DacService(catalog, model=ExplodingModel())
    result = await service.recommend(
        DacRecommendRequestV1(use_case="A coding assistant for Python services")
    )
    assert result.candidates
    assert result.model_backed is False
    assert any("without a model call" in note for note in result.notes)


@pytest.mark.anyio
async def test_model_may_reorder_but_never_introduce_a_model(catalog: DacCatalog):
    """The model reorders a host-validated list; anything it invents is dropped."""
    baseline = DacService(catalog).\
        _shortlist(DacRecommendRequestV1(use_case="A coding assistant for Python services"))
    assert len(baseline) > 1
    reversed_ids = [candidate.model_id for candidate in reversed(baseline)]

    provider = ReorderingModel(reversed_ids)
    service = DacService(catalog, model=provider)
    result = await service.recommend(
        DacRecommendRequestV1(use_case="A coding assistant for Python services")
    )
    returned = [candidate.model_id for candidate in result.candidates]
    assert returned == reversed_ids
    assert "hallucinated/model-that-does-not-exist" not in returned
    assert result.model_backed is True
    assert result.summary == "Pick the first one."
    assert result.candidates[0].rationale


@pytest.mark.anyio
async def test_model_can_promote_a_modern_model_beyond_the_visible_shortlist(
    catalog: DacCatalog,
):
    request = DacRecommendRequestV1(
        use_case=(
            "Two use cases: 1. Coding assistant "
            "2. Document/image extraction solution"
        ),
        limit=5,
    )
    provider = ReorderingModel(["Qwen/Qwen3.6-35B-A3B"])

    result = await DacService(catalog, model=provider).recommend(request)

    assert len(result.candidates) == request.limit
    assert result.candidates[0].model_id == "Qwen/Qwen3.6-35B-A3B"


@pytest.mark.anyio
async def test_recommender_uses_the_configured_model_preference(catalog: DacCatalog):
    """Whichever model the user pinned is the one that gets asked."""

    class Preference:
        def resolve_aliases(self) -> dict[str, str]:
            return {"planner": "my-pinned-model", "_provider": "local"}

    provider = ReorderingModel(["placeholder"])
    service = DacService(catalog, model=provider, preference=Preference())
    await service.recommend(DacRecommendRequestV1(use_case="A coding assistant"))
    assert provider.seen_aliases == {"planner": "my-pinned-model", "_provider": "local"}


def test_a_measured_configuration_reports_oracles_numbers_not_modeled_ones(
    client: TestClient,
):
    """When the badge says "measured", the metrics beside it must be measured.

    Oracle publishes gpt-oss-120b on OAI_H100_X2 at concurrency 32 for the Chat
    scenario. The roofline predicts ~13% higher there, and showing that under a
    "measured" label is the one case where the confidence badge would actively
    mislead rather than merely approximate.
    """
    response = client.post(
        "/api/v1/dac/estimate",
        json={
            "model_id": "openai/gpt-oss-120b",
            "shape": "OAI_H100_X2",
            "concurrency": 32,
            "prompt_tokens": 100,
            "response_tokens": 100,
        },
    )
    assert response.status_code == 200
    body = response.json()
    assert body["confidence"]["tier"] == "measured"
    published = body["published"]
    assert published is not None
    assert body["performance"]["inference_speed_tps"] == pytest.approx(
        published["inference_speed_tps"]
    )
    assert body["performance"]["ttft_s"] == pytest.approx(published["ttft_s"])
    assert any("published measurements" in note for note in body["notes"])


def test_scaling_a_measured_row_to_many_units_falls_back_to_the_model(
    client: TestClient,
):
    """Oracle benchmarks one unit; multiplying that up is modelling, not measuring."""
    response = client.post(
        "/api/v1/dac/estimate",
        json={
            "model_id": "openai/gpt-oss-120b",
            "shape": "OAI_H100_X2",
            "units": 4,
            "concurrency": 32,
            "prompt_tokens": 100,
            "response_tokens": 100,
        },
    )
    assert response.status_code == 200
    body = response.json()
    assert body["performance"]["inference_speed_tps"] != pytest.approx(
        body["published"]["inference_speed_tps"]
    )
    assert not any("published measurements" in note for note in body["notes"])


def test_benchmarked_shapes_stay_selectable_even_when_not_importable(
    client: TestClient, catalog: DacCatalog
):
    """The only measured configurations must remain reachable.

    Oracle's published grids run on an OpenAI-reserved shape that is not offered
    for model import. Exposing only importable shapes would hide the one tier
    backed by real measurements behind a modeled number.
    """
    body = client.get("/api/v1/dac/catalog").json()
    by_id = {model["id"]: model for model in body["models"]}
    gpt_oss = by_id["openai/gpt-oss-120b"]
    assert "OAI_H100_X2" in gpt_oss["benchmarked_shapes"]

    shapes = {shape["key"]: shape for shape in body["shapes"]}
    assert shapes["OAI_H100_X2"]["importable"] is False

    # And most models have no benchmarked shape at all, so the field is not
    # quietly duplicating the validated list.
    assert not by_id["Qwen/Qwen3-32B"]["benchmarked_shapes"]
