from __future__ import annotations

import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


SKILL_DIR = Path(__file__).resolve().parents[1]
TOOL = SKILL_DIR / "src" / "architecture_tool.py"


def north_generated_code() -> str:
    return """# Candidate generated by North Mini Code.
from pathlib import Path
from diagrams import Cluster, Diagram, Edge
from diagrams.generic.blank import Blank

OUTPUT_STEM = str(Path(__file__).resolve().parent / "architecture")

with Diagram('Order platform', filename=OUTPUT_STEM, outformat=['svg'], show=False, direction='LR'):
    with Cluster('Private backend'):
        node_000 = Blank('Orders API\\n[service]')
        node_001 = Blank('Orders DB\\n[database]')
    node_002 = Blank('Web app\\n[client]')
    node_000 >> Edge(label='SQL') >> node_001
    node_002 >> Edge(label='HTTPS') >> node_000
"""


def request(*, formats: list[str] | None = None, mode: str = "fallback") -> dict:
    return {
        "schema_version": "1",
        "spec": {
            "title": "Order platform",
            "provider": "oci",
            "direction": "LR",
            "components": [
                {"id": "web", "label": "Web app", "kind": "client"},
                {"id": "api", "label": "Orders API", "kind": "service"},
                {"id": "db", "label": "Orders DB", "kind": "database"},
            ],
            "edges": [
                {"source": "web", "target": "api", "label": "HTTPS"},
                {"source": "api", "target": "db", "label": "SQL"},
            ],
            "boundaries": [
                {"id": "backend", "label": "Private backend", "component_ids": ["api", "db"]}
            ],
            "assumptions": ["TLS terminates at the API."],
            "unresolved_ambiguities": [],
        },
        "output_formats": formats or ["svg"],
        "render_mode": mode,
    }


def invoke(payload: dict, output_dir: Path) -> tuple[subprocess.CompletedProcess[bytes], dict]:
    completed = subprocess.run(
        [sys.executable, str(TOOL), "--output-dir", str(output_dir)],
        input=json.dumps(payload).encode("utf-8"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=10,
        check=False,
    )
    return completed, json.loads(completed.stdout)


class ArchitectureToolTests(unittest.TestCase):
    def test_fallback_generates_valid_declared_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)
            completed, result = invoke(request(), output)
            self.assertEqual(completed.returncode, 0, completed.stderr.decode())
            self.assertEqual(result["status"], "succeeded")
            self.assertEqual(result["renderer"], "deterministic-svg-fallback-v1")
            self.assertEqual(result["validation"]["source_origin"], "deterministic-fallback")
            names = {item["name"] for item in result["artifacts"]}
            self.assertEqual(
                names,
                {"architecture-spec.json", "diagram.py", "architecture.svg", "validation-report.json"},
            )
            for artifact in result["artifacts"]:
                content = (output / artifact["path"]).read_bytes()
                self.assertEqual(artifact["size_bytes"], len(content))
                self.assertEqual(artifact["sha256"], hashlib.sha256(content).hexdigest())
            svg = (output / "architecture.svg").read_text(encoding="utf-8")
            self.assertIn("Orders API", svg)
            self.assertIn("Private backend", svg)
            self.assertNotIn("<script", svg.lower())

    def test_outputs_are_deterministic(self) -> None:
        with tempfile.TemporaryDirectory() as first, tempfile.TemporaryDirectory() as second:
            first_result, first_json = invoke(request(), Path(first))
            second_result, second_json = invoke(request(), Path(second))
            self.assertEqual(first_result.returncode, 0)
            self.assertEqual(second_result.returncode, 0)
            self.assertEqual(first_json, second_json)
            for name in ("architecture-spec.json", "diagram.py", "architecture.svg", "validation-report.json"):
                self.assertEqual((Path(first) / name).read_bytes(), (Path(second) / name).read_bytes())

    def test_supplied_model_code_is_validated_and_preserved(self) -> None:
        payload = request()
        payload["diagram_code"] = north_generated_code()
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)
            completed, result = invoke(payload, output)
            self.assertEqual(completed.returncode, 0, completed.stderr.decode())
            self.assertEqual(result["status"], "succeeded")
            self.assertEqual(result["validation"]["source_origin"], "model-generated")
            self.assertEqual(result["validation"]["semantic_code"]["status"], "passed")
            self.assertEqual((output / "diagram.py").read_text(), north_generated_code())

    def test_supplied_model_code_fails_closed_on_security_attempts(self) -> None:
        valid = north_generated_code()
        attempts = {
            "shell": (valid + "\n__import__('os').system('id')\n", "STATIC_VALIDATION_FAILED"),
            "import": (
                valid.replace(
                    "from diagrams.generic.blank import Blank",
                    "from subprocess import run",
                ),
                "STATIC_VALIDATION_FAILED",
            ),
            "path": (
                valid.replace(
                    'OUTPUT_STEM = str(Path(__file__).resolve().parent / "architecture")',
                    'OUTPUT_STEM = str(Path("/tmp/escape"))',
                ),
                "SEMANTIC_VALIDATION_FAILED",
            ),
        }
        for name, (code, expected_error) in attempts.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as directory:
                payload = request()
                payload["diagram_code"] = code
                completed, result = invoke(payload, Path(directory))
                self.assertEqual(completed.returncode, 3)
                self.assertEqual(result["status"], "failed")
                self.assertEqual(result["error"]["code"], expected_error)

    def test_supplied_model_code_must_match_spec(self) -> None:
        payload = request()
        payload["diagram_code"] = north_generated_code().replace(
            "Orders DB\\n[database]", "Different database\\n[database]"
        )
        with tempfile.TemporaryDirectory() as directory:
            completed, result = invoke(payload, Path(directory))
            self.assertEqual(completed.returncode, 3)
            self.assertEqual(result["error"]["code"], "SEMANTIC_VALIDATION_FAILED")

    def test_png_fallback_is_an_explicit_typed_error(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            completed, result = invoke(request(formats=["svg", "png"]), Path(directory))
            self.assertEqual(completed.returncode, 4)
            self.assertEqual(result["status"], "failed")
            self.assertEqual(result["error"]["code"], "PNG_RENDERER_UNAVAILABLE")

    def test_rejects_unknown_edge_reference(self) -> None:
        payload = request()
        payload["spec"]["edges"][0]["target"] = "missing"
        with tempfile.TemporaryDirectory() as directory:
            completed, result = invoke(payload, Path(directory))
            self.assertEqual(completed.returncode, 2)
            self.assertEqual(result["error"]["code"], "INVALID_INPUT")

    def test_rejects_overlapping_boundaries(self) -> None:
        payload = request()
        payload["spec"]["boundaries"].append(
            {"id": "duplicate", "label": "Duplicate", "component_ids": ["api"]}
        )
        with tempfile.TemporaryDirectory() as directory:
            completed, result = invoke(payload, Path(directory))
            self.assertEqual(completed.returncode, 2)
            self.assertEqual(result["error"]["code"], "INVALID_INPUT")

    def test_rejects_unknown_fields(self) -> None:
        payload = request()
        payload["network"] = "host"
        with tempfile.TemporaryDirectory() as directory:
            completed, result = invoke(payload, Path(directory))
            self.assertEqual(completed.returncode, 2)
            self.assertEqual(result["error"]["code"], "INVALID_INPUT")


if __name__ == "__main__":
    unittest.main()
