"""The Oracle SKU vocabulary, and the separately-owned rate card beside it.

Two files, deliberately kept apart:

`data/skus/catalog.json` is machine-derived from Oracle's UCM Service
Descriptions PDF — official names, part numbers, and the *unit* each SKU bills
in. It is a fact about Oracle's catalog and is regenerated by
`scripts/build_sku_catalog.py`, never edited by hand.

`data/skus/rates.json` is the money, and it is the user's. That document
publishes no prices, so the dollar figures are seeded from public list pricing,
marked unverified, and expected to be replaced with contracted rates. Keeping
them in a separate file means regenerating the catalog can never quietly
overwrite a rate someone confirmed, and a rate edit can never invent a SKU.

Only a SKU that appears in *both* can produce a dollar figure.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).resolve().parent / "data" / "skus"
HOURS_PER_YEAR = 8760


@dataclass(frozen=True)
class SkuEntry:
    part_number: str
    name: str
    metric: str
    category: str
    retired: bool


@dataclass
class SkuRate:
    """A price the user owns, for a SKU the catalog knows about."""

    key: str
    unit: str
    value: float
    label: str
    verified: bool = False
    aliases: tuple[str, ...] = ()
    part_number: str | None = None
    note: str = ""

    def to_json(self) -> dict[str, Any]:
        return {
            "key": self.key,
            "part_number": self.part_number,
            "unit": self.unit,
            "value": self.value,
            "label": self.label,
            "verified": self.verified,
            "aliases": list(self.aliases),
            "note": self.note,
        }


@dataclass
class RateCard:
    currency: str = "USD"
    hours_per_year: int = HOURS_PER_YEAR
    rates: dict[str, SkuRate] = field(default_factory=dict)
    source_urls: tuple[str, ...] = ()

    @property
    def fully_verified(self) -> bool:
        return bool(self.rates) and all(rate.verified for rate in self.rates.values())


def _normalize(text: str) -> str:
    # "4xH100" and "2 x A100" are how notes actually write a GPU count, and
    # collapsing the multiplier into the model name would hide the name from a
    # word-boundary search. Split it off before flattening the rest.
    text = re.sub(r"\b(\d+)\s*[x×]\s*(?=[A-Za-z])", r"\1 ", text)
    return re.sub(r"[^a-z0-9]+", " ", text.lower()).strip()


class SkuCatalog:
    """Loads the vendored catalog and the rate card, and matches prose to SKUs."""

    def __init__(
        self, data_dir: Path | None = None, *, rates_path: Path | None = None
    ) -> None:
        self._dir = data_dir or DATA_DIR
        self._rates_path = rates_path or (self._dir / "rates.json")
        self._entries: dict[str, SkuEntry] = {}
        self._card = RateCard()
        self._load_catalog()
        self._seed_rates()
        self.reload_rates()

    def _seed_rates(self) -> None:
        """Copy the vendored rate card into the user's own file, once.

        After that the two diverge on purpose: shipping a new seed must never
        overwrite a rate someone confirmed or replaced with their own.
        """
        seed = self._dir / "rates.json"
        if self._rates_path == seed or self._rates_path.exists() or not seed.exists():
            return
        self._rates_path.parent.mkdir(parents=True, exist_ok=True)
        self._rates_path.write_text(seed.read_text(encoding="utf-8"), encoding="utf-8")

    def _load_catalog(self) -> None:
        try:
            raw = json.loads((self._dir / "catalog.json").read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return
        for item in raw.get("entries", []):
            part = str(item.get("part_number") or "").strip()
            if not part:
                continue
            self._entries[part] = SkuEntry(
                part_number=part,
                name=str(item.get("name") or "").strip(),
                metric=str(item.get("metric") or "").strip(),
                category=str(item.get("category") or "").strip(),
                retired=bool(item.get("retired")),
            )

    # -- rate card -------------------------------------------------------

    @property
    def rates_path(self) -> Path:
        return self._rates_path

    def reload_rates(self) -> RateCard:
        try:
            raw = json.loads(self.rates_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            self._card = RateCard()
            return self._card
        card = RateCard(
            currency=str(raw.get("currency") or "USD"),
            hours_per_year=int(raw.get("hours_per_year") or HOURS_PER_YEAR),
            source_urls=tuple(str(item) for item in raw.get("source_urls", [])),
        )
        for item in raw.get("rates", []):
            part = str(item.get("part_number") or "").strip()
            # A rate for a part number the catalog does not list is dropped: the
            # catalog is the authority on what Oracle actually sells, so a rate
            # without one would let a typo become a billable line item.
            if not part or part not in self._entries:
                continue
            card.rates[part] = self._rate(item, key=part, part_number=part)
        for item in raw.get("synthetic_rates", []):
            key = str(item.get("key") or "").strip()
            if key:
                card.rates[key] = self._rate(item, key=key, part_number=None)
        self._card = card
        return card

    @staticmethod
    def _rate(item: dict[str, Any], *, key: str, part_number: str | None) -> SkuRate:
        return SkuRate(
            key=key,
            part_number=part_number,
            unit=str(item.get("unit") or "").strip(),
            value=max(0.0, float(item.get("value") or 0.0)),
            label=str(item.get("label") or "").strip(),
            verified=bool(item.get("verified")),
            aliases=tuple(str(alias) for alias in item.get("aliases", [])),
            note=str(item.get("note") or "").strip(),
        )

    def save_rates(self, updates: dict[str, dict[str, Any]]) -> RateCard:
        """Persist edited values, leaving everything else in the file intact."""
        raw = json.loads(self.rates_path.read_text(encoding="utf-8"))
        for group, id_key in (("rates", "part_number"), ("synthetic_rates", "key")):
            for item in raw.get(group, []):
                update = updates.get(str(item.get(id_key) or ""))
                if not update:
                    continue
                if "value" in update:
                    item["value"] = max(0.0, float(update["value"]))
                if "verified" in update:
                    item["verified"] = bool(update["verified"])
        self.rates_path.write_text(
            json.dumps(raw, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        return self.reload_rates()

    # -- lookup ----------------------------------------------------------

    @property
    def card(self) -> RateCard:
        return self._card

    @property
    def size(self) -> int:
        return len(self._entries)

    def entry(self, part_number: str) -> SkuEntry | None:
        return self._entries.get(part_number.strip().upper())

    def rate(self, key: str) -> SkuRate | None:
        return self._card.rates.get(key.strip())

    def priced(self) -> list[SkuRate]:
        return sorted(self._card.rates.values(), key=lambda rate: rate.label)

    def describe_priced(self) -> list[dict[str, Any]]:
        """The menu handed to the model: only SKUs that can produce a figure.

        The rate card's own label leads, because it is curated and complete;
        Oracle's catalog name rides along beside it, since it is machine-derived
        from the PDF and occasionally loses a trailing word to the table layout.
        """
        rows: list[dict[str, Any]] = []
        for rate in self.priced():
            entry = self.entry(rate.part_number) if rate.part_number else None
            row = {
                "sku": rate.key,
                "name": rate.label,
                "unit": rate.unit,
                "also_known_as": list(rate.aliases),
            }
            if entry:
                row["oracle_name"] = entry.name
            rows.append(row)
        return rows

    def match(self, text: str) -> list[SkuRate]:
        """Every priced SKU an alias or part number of which appears in `text`."""
        haystack = _normalize(text)
        found: list[SkuRate] = []
        for rate in self.priced():
            names = [*rate.aliases]
            if rate.part_number:
                names.append(rate.part_number)
            if any(re.search(rf"\b{re.escape(_normalize(n))}\b", haystack) for n in names if n):
                found.append(rate)
        return found
